version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: html-proofer
    versions:
    - 3.18.6
    - 3.18.8
    - 3.19.0
  - dependency-name: nokogiri
    versions:
    - 1.11.2
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  assignees:
  - Nereare
  ignore:
  - dependency-name: github-pages
    versions:
    - "212"
    - "213"
