title            : Grimoire
email            : igorpadoim@gmail.com
description      : A jekyll quasi-wiki for RPG-oriented worldbuilding.
twitter_username : nereare
github_username  : nereare

markdown         : kramdown
plugins          :
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Relativize links in collections
relative_links   :
  enabled        : true
  collections    : true

# Collections
collections:
  adventures:
    output       : true
    sort_by      : title
  monsters:
    output       : true
    sort_by      : title

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CHANGELOG.md
  - CODE-OF-CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE.md
  - OGL.md
  - README.md
