title            : Grimoire
email            : igorpadoim@gmail.com
description      : A jekyll quasi-wiki for RPG-oriented worldbuilding.

markdown         : kramdown
plugins          :
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Collections
collections      :
  adventures     :
    output       : true
    sort_by      : title
  chapters       :
    output       : true
    sort_by      : book
  monsters       :
    output       : true
    sort_by      : title
  settlements    :
    output       : true
    sort_by      : title
  spells         :
    output       : true
    sort_by      : title

exclude          :
  - Gemfile
  - Gemfile.lock
  - script/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CHANGELOG.md
  - CODE-OF-CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE.md
  - OGL.md
  - README.md
