source 'https://rubygems.org'

gem 'jekyll', '~>4.4'
group :jekyll_plugins do
  gem 'just-the-docs', '~>0.12'
  gem 'kramdown', '~>2.5'
  gem 'webrick', '~>1.9'
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem 'tzinfo', '~>2.0'
  gem 'tzinfo-data'
end
gem 'wdm', '~>0.2', :install_if => Gem.win_platform?
