source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'github-pages'
  gem 'just-the-docs', '~> 0.3.3'
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem 'tzinfo', '~> 2.0'
  gem 'tzinfo-data', '~> 1.2020.4'
end
gem 'wdm', '~> 0.1.1', :install_if => Gem.win_platform?
