name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Dependencies
      run: |
        gem install bundler -v 2.0.2
        bundle install --retry 3
        chmod +x ./script/cibuild.sh
    - name: Run Tests
      run: |
        ./script/cibuild.sh
